### ISSUE TITLE
Image badges are not working in Github

### ISSUE THREAD

**Issue by activatedgeek** [CenturyLinkLabs/imagelayers#28]
Please have a look at this repository: [https://github.com/activatedgeek/docker-ansible-ubuntu](https://github.com/activatedgeek/docker-ansible-ubuntu).

The second badge is from ImageLayers.io.

The same error occurs on the imagelayers repository as well. See [https://github.com/CenturyLinkLabs/imagelayers](https://github.com/CenturyLinkLabs/imagelayers).

A snapshot of missing badge image: 
<img width="980" alt="screen shot 2016-04-24 at 5 22 25 pm" src="https://cloud.githubusercontent.com/assets/3909933/14767356/24ccbb0c-0a41-11e6-9179-46ed1994289c.png">

The raw link is otherwise: [https://badge.imagelayers.io/centurylink/imagelayers-api.svg](https://badge.imagelayers.io/centurylink/imagelayers-api.svg) which works.

**Comment by ntfrnzn** [comment]
This appears to be triggered by github image caching, see for instance https://help.github.com/articles/why-do-my-images-have-strange-urls/.  Imagelayers.io hosting moved last week, so that may explain why the previously cached image is not available.  This issue https://github.com/github/markup/issues/224 seems relevant?  But old.

**Comment by activatedgeek** [comment]
@ntfrnzn Indeed! Thanks for the heads up! I did try all the steps Github article to no avail. Any other ideas? I have also mailed Github support already. It looks like a problem with their proxying service.
